#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"
checkpoint="checkpoints/smoke_step_100.pt"
output="outputs/generation_suite_100_step.md"

if [[ ! -f "$checkpoint" ]]; then
  echo "Missing checkpoint: $checkpoint" >&2
  exit 1
fi

cat > "$output" <<'HEADER'
# Aletheia Tiny: 100-Step Generation Suite

**Checkpoint:** `checkpoints/smoke_step_100.pt`  
**Decoding:** 128 generated bytes per prompt; temperature 0.8; top-k 16  
**Sampling:** Seed fixed separately for each prompt, as listed below  
**Output policy:** The model outputs below are captured verbatim. No correction, cleanup, or post-processing has been applied.

HEADER

emit_sample() {
  local title="$1"
  local prompt="$2"
  local seed="$3"

  {
    printf '## %s\n\n' "$title"
    printf '**Prompt**\n\n```text\n%s\n```\n\n' "$prompt"
    printf '**Sampling seed:** `%s`\n\n' "$seed"
    printf '**Raw output**\n\n```text\n'
  } >> "$output"

  python3 src/generate.py \
    --checkpoint "$checkpoint" \
    --prompt "$prompt" \
    --tokens 128 \
    --temperature 0.8 \
    --top-k 16 \
    --seed "$seed" \
    --device cpu >> "$output"

  printf '\n```\n\n' >> "$output"
}

emit_sample "In-domain continuation: persistence" \
  'The Persistence Barrier. The "I" is built on the foundation of' 101
emit_sample "In-domain project prompt: Aletheia" \
  'Aletheia: the geometry of meaning is' 102
emit_sample "Novel factual prompt" \
  'What is the capital of France?' 103
emit_sample "Novel procedural prompt" \
  'Write a recipe for pancakes:' 104
emit_sample "Novel descriptive prompt" \
  'A hummingbird drinks nectar from a flower because' 105
emit_sample "Novel arithmetic prompt" \
  '2 + 2 =' 106

echo "Wrote $output"
